BASE: ['inference_base.yaml']

VAL_OUTPUT_PATH: "" # The path of inference output directory.

DATASET:
  DATASET_NAME: 'inference_demo'
  VAL_IMAGE_PATH: 'MR/PublicValidation/imagesVal'
  VAL_CHANGE_SPACING: False
  DA:
    DO_MIRROR: False
  FINE:
    SIZE: [ 96, 192, 192 ]
    PREPROCESS_SIZE: [ 192, 192, 96 ]

MODEL:
  FINE:
    BASE_NUM_FEATURES: 16
    MAX_NUM_FEATURES: 200
    DEPTHS: [2, 2, 2, 2]
    NUM_HEADS: [4, 4, 4, 4]
    WINDOW_SIZE: [3, 4, 4]
    MLP_RATIO: 1.
    DROP_PATH_RATE: 0.1

VAL:
  IS_CROP: False
  TTA: True
