BASE: ["preprocess_base.yaml"]

TRAINING_TYPE: 'coarse-fine'
FINE_MODEL_PATH: "/ChenQiang/GitHubProject/MICCAI24_FLARE/Lijiaxi/TPH_old/save_pth/TJUvil_CT_PlabelV3_regis_same_diff_a800_240819_144355"
CHECK_POINT_NAME: "275_checkpoint.pth"


# stage1 - preprocess
MR_DATA_PREPROCESS:
  ROOT_PATH: "/ChenQiang/DataSet/Medical/MICCAI24_FLARE/Dataset"
  MR_RAW_DATA_PATH: "MR/Training/LLD-MMRI-3984"
#  PSUEDO_LABEL_PATH: "MR/Training/PLabel/LLD-MMRI-3984-T2_tmp_v3_softmax" # inference psuedo label path
  LLD_TEMP_MR_RAW_DATA_PATH:  "MR/Training/LLD-MMRI-3984-demo" # filter C+Delay data
  DATA_PAIR_PATH: "MR/Training/preprocess_data_pair" # using symlink and rename to save Hard Disk Space. it's recoder source filename and symlink name pair. it's json file path.
  TEMP_PREPROCESSED_PSUEDO_LABEL_PATH: "MR/Training/PLabel/LLD-MMRI-3984-T2_tmp_demo" # test
  # stage4 regis
  REGIS:
    OUTPUT_PATH: 'MR/Training/regis_data/LLD-MMRI-3984-regis-demo'
  # stage3 - generate psuedo label
  # filter psuedo label
  CT_GT_PATH: "CT/CT_label_300"
  OUTPUT_EACH_CT_LABELS_NUM_STATIC_PATH: 'static_info/label_class_static_demo.csv'
  FILTER_CASE_SAVE_PATH: "static_info/filter_plabel_lld_demo.csv" # save filtered case infos . it's csv file path.
  # stage2 - preprocess
  PREPROCESSED_RAW_PATH: 'MR/Training/PLabel/LLD-MMRI-3984-regis_same_demo' # filtered bad psuedo label case
  PREPROCESSED_PSUEDO_LABEL_PATH: 'MR/Training/PLabel_image/LLD-MMRI-3984-regis_same_demo' #
  BAD_CASE_PATH: 'MR/Training/preprocess_data_pair/LLD_demo.json' # preprocessed fail case file. it's json file path.

  # stage5 output_data
  IS_LLD_REGIS_DATA: True


INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True
  SAVE_SOFTMAX: False

VERSION: "exp_6_240826"


VAL:
  TTA: False
  EVAL_OUTPUT_RESULT: "/ChenQiang/DataSet/Medical/MICCAI24_FLARE/validation_result/eval_result/exp_6"

# final stage
DATASET:

  BASE_DIR: "/ChenQiang/DataSet/Medical/MICCAI24_FLARE/Dataset"
  TRAIN_IMAGE_PATH: 'MR/Training/PLabel_image/LLD-MMRI-3984-T2_v_tmp'
  TRAIN_MASK_PATH: 'MR/Training/PLabel/LLD-MMRI-3984-T2_v_tmp'
  IS_ABDOMEN_CROP: False
  COARSE:
    PROPRECESS_PATH: "TPH_processed_data/coarse/small_network_base/MR_lld_plabel_v_regis_diff_softmax_demo"
  FINE:
    PROPRECESS_PATH: "TPH_processed_data/fine/small_network_base/MR_lld_plabel_v_regis_diff_softmax_demo"
    SIZE: [ 96, 192, 192 ]
    PREPROCESS_SIZE: [ 192, 192, 96 ]