BASE: ["preprocess_base.yaml"]

# stage1 - preprocess
MR_DATA_PREPROCESS:
  STAGE: 1

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True
  SAVE_SOFTMAX: False

VERSION: "preprocess_step1_CT"

# final stage
DATASET:
  TRAIN_IMAGE_PATH: 'datasets/CT/CT_image'
  TRAIN_MASK_PATH: 'datasets/CT/CT_label'
  IS_ABDOMEN_CROP: False
  COARSE:
    PROPRECESS_PATH: "datasets/processed_data/coarse/small_segnet/ct"
  FINE:
    PROPRECESS_PATH: "datasets/processed_data/fine/small_segnet/ct"
