BASE: ["preprocess_base.yaml"]

# stage1 - preprocess
MR_DATA_PREPROCESS:
  STAGE: 2
  MR_RAW_DATA_PATH: "datasets/MR/Training/AMOS_MR_good_spacing-833"
  TEMP_MR_RAW_DATA_PATH:  "datasets/MR/Training/AMOS_MR_good_spacing-833" # filter C+Delay data
  DATA_PAIR_PATH: "datasets/MR/Training/preprocess_data_pair" # using symlink and rename to save Hard Disk Space. it's recoder source filename and symlink name pair. it's json file path.
  TEMP_PREPROCESSED_PSUEDO_LABEL_PATH: "datasets/MR/Training/PLabel/AMOS_MR_good_spacing-833_tmp_demo" # test
  CT_GT_PATH: "datasets/CT/CT_label"
  OUTPUT_EACH_CT_LABELS_NUM_STATIC_PATH: 'datasets/static_info/label_class_static_demo.csv'
  FILTER_CASE_SAVE_PATH: "datasets/static_info/filter_plabel_amos_demo.csv" # save filtered case infos . it's csv file path.
  BAD_CASE_PATH: 'datasets/MR/Training/preprocess_data_pair/amos_demo.json' # preprocessed fail case file. it's json file path.
  IS_LLD_REGIS_DATA: False

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True
  SAVE_SOFTMAX: False

VERSION: "preprocess_step2_amos"

# final stage
DATASET:
  TRAIN_IMAGE_PATH: 'datasets/MR/Training/PLabel_image/AMOS_MR_good_spacing-833'
  TRAIN_MASK_PATH: 'datasets/MR/Training/PLabel/AMOS_MR_good_spacing-833'
  IS_ABDOMEN_CROP: False
  COARSE:
    PROPRECESS_PATH: "datasets/processed_data/coarse/small_segnet/MR_amos_stage2"
  FINE:
    PROPRECESS_PATH: "datasets/processed_data/fine/small_segnet/MR_amos_stage2"
