BASE: ['predict_base.yaml']

FINE_MODEL_PATH: "/ChenQiang/GitHubProject/MICCAI24_FLARE/Lijiaxi/TPH_old/save_pth/TJUvil_CT_PlabelV2_regis_same_diffp1_a800_240818_041516" # CT+real mr plabel crop
CHECK_POINT_NAME: "250_checkpoint.pth"
VAL_OUTPUT_PATH: "/ChenQiang/DataSet/Medical/MICCAI24_FLARE/Dataset/MR/Training/PLabel/LLD-MMRI-3984-T2_tmp_v3_softmax"

DATASET:
  DATASET_NAME: 'CT_PlabelV3_lld_softmax'
  BASE_DIR: '/ChenQiang/DataSet/Medical/MICCAI24_FLARE/Dataset'
  VAL_IMAGE_PATH: 'MR/Training/LLD-MMRI-3984-T2_tmp'

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: False
  SAVE_SOFTMAX: True
