BASE: ["train_base.yaml"]

DATASET:
  DATASET_NAME: 'CT_fakeMR'
  FINE:
    SPLIT_PREPROCESS_PATH: [
      'processed_data/fine/small_segnet/ct',
      # TODO 把风格迁移输出的FAKE MR路径放到这里,
    ]
    PROPRECESS_PATH: "processed_data/fine/combined_data/big_segnet"


