

TRAINING_TYPE: 'fine'

DATASET:
  DATASET_NAME: 'PlabelV1'
  BASE_DIR: "/ChenQiang/DataSet/Medical/MICCAI24_FLARE/Dataset"
  FINE:
    PROPRECESS_PATH: "Preprocess_CT_FAKEMR/PLABEL_V1"
  DA:
    DO_MIRROR: True

DATALOADER:
  BATCH_SIZE: 1
  NUM_WORKERS: 8

TRAIN:
  EPOCHS: 300
  MULTI_TASK:
    IS_OPEN: False
    CLASS_NUM: 2
  SELECT_IMPORT_VOXEL:
    IS_OPEN: False
    DROP_VOXEL: False
    UPDATE_LOSS_WEIGHT: False

LOSS:
  FLARE24_CHANGE_WEIGHT: False
